### ISSUE TITLE
Error on device update!

### ISSUE THREAD

**Issue by HikingMike** [Ceerbeerus/beerbolaget#3]
Hi
I can't figure out whats wrong... After a restart of HASS (one of many) Beerbolaget went from working fine (and much appreciated) to not working at all. This is the error from log:

Log Details (ERROR)
Tue Nov 19 2019 15:56:42 GMT+0100 (centraleuropeisk normaltid)
beerbolaget: Error on device update!
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/helpers/entity_platform.py", line 292, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/helpers/entity.py", line 448, in async_device_update
    await self.async_update()
  File "/home/homeassistant/.homeassistant/custom_components/beerbolaget/sensor.py", line 66, in async_update
    self._attributes['release_date'] = await self._beer_handler.get_release()
  File "/home/homeassistant/.homeassistant/custom_components/beerbolaget/__init__.py", line 122, in get_release
    return await self.beer_handle.get_release()
  File "/srv/homeassistant/lib/python3.7/site-packages/beerbolaget/beer.py", line 80, in get_release
    return self.release.split('T')[0]
AttributeError: 'NoneType' object has no attribute 'split'

Have I done soemthing to wreck it? Can't recall I did any changes. Stopped HASS and restarted due to maintenance to NAS where database resides.

Running version 0.101.3 in a virtual environment with python 3.7.3.
What puzzles me is that it worked perfectly fine before...

Kind Regards
Mikael

**Comment by Ceerbeerus** [comment]
Hi!

Which version of Beerbolaget do you run? 
0.3.11 is the latest, which happens to contain an update to match API changes made by systembolaget. 

If you're on a older version, try upgrading. 

If this doesn't work I would guess you have restarted to many times in a row and hit the API request limit.

(sorry for the late response, my notifications broke)

**Comment by HikingMike** [comment]
Hi!
Just pulled down your updated version and it works again. Excellent! :)
Thanks alot for updating. Much appreciated.

/Mikael
