### ISSUE TITLE
Sensor not working

### ISSUE THREAD

**Issue by oskarax** [Ceerbeerus/beerbolaget#6]
Hi, beerbolaget sensor is gone from my entities. Didn't do anything. The this error in the logs. Tried to uninstall och install again but still the same. Whats the issue here?

beerbolaget: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 292, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 459, in async_device_update
    await self.async_update()
  File "/config/custom_components/beerbolaget/sensor.py", line 72, in async_update
    '%Y-%m-%d').date()
  File "/usr/local/lib/python3.7/_strptime.py", line 577, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "/usr/local/lib/python3.7/_strptime.py", line 359, in _strptime
    (data_string, format))
ValueError: time data 'No release could be found.' does not match format '%Y-%m-%d'

**Comment by Ceerbeerus** [comment]
This error is fixed 0.3.13
